version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: k3_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: k3_db
    ports:
      - "5432:5432"
    volumes:
      - k3_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: k3_minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - k3_miniodata:/data
    restart: unless-stopped

volumes:
  k3_pgdata:
  k3_miniodata:
